[package]
name = "node_crunch"
version = "0.1.0"
authors = ["Willi Kappler <grandor@gmx.de"]
description = "A crate for distributed computing"
keywords = ["distribute", "network", "numeric", "computing", "cluster", "hpc"]
categories = ["Network programming", "Science"]
edition = "2018"

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
bincode = "1"
rand = "0.7"
#crossbeam = "0.8"
thiserror = "1.0"
threadpool = "1.0"


[profile.release]
lto = true
