[package]
name = "node_crunch"
version = "0.1.0"
authors = ["Willi Kappler <grandor@gmx.de"]
description = "A crate for distributed computing"
keywords = ["distribute", "network", "numeric", "computing", "cluster"]
categories = ["Network programming", "Science"]
edition = "2018"

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
rand = "0.7"
message-io = "0.4"

[profile.release]
lto = true
