[package]
name = "node_crunch"
version = "0.1.0"
authors = ["Willi Kappler <grandor@gmx.de"]
description = "A crate for distributed computing"
keywords = ["distribute", "network", "numeric", "computing", "cluster"]
categories = ["Network programming", "Science"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
log = "0.4"
log4rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"

[profile.release]
lto = true
